# Generated by Django 4.0.4 on 2022-04-17 13:15

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('housenumber', models.CharField(max_length=100)),
                ('police', models.IntegerField(blank=True)),
                ('hospital', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('identiy_number', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(default='', max_length=300)),
                ('neighbourhood', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodwatch.neighbourhood')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('post', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(blank=True, default='', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='neighbour', to='neighbourhoodwatch.profile'),
        ),
    ]
