# Generated by Django 4.0.4 on 2022-04-17 19:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0004_business_description_alter_business_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
