# Generated by Django 4.0.4 on 2022-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0006_alter_post_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
